### ISSUE TITLE
How to nest to <td> elements with attribute colspan 3 into <tr> child-row in vue-tables-2

### ISSUE THREAD

**Issue by GlebShu** [matfish2/vue-tables-2#909]
I have a problem. I need to place two elements <td> inside child-row with attribute colspan 3. I tried to create template and insert this to but instead it applies to element.

What I want to get:

```
<tr class="VueTables__row ">...</tr>
<tr class="VueTables__child-row">
 <td tabindex="0" colspan="3">
    <span>...</span>
 </td>
<td tabindex="0" colspan="3">
    <span>...</span>
 </td>
</tr>
```

As a result, the following is displayed in the DOM:

```
<tr class="VueTables__row ">...</tr>
<tr class="VueTables__child-row">
 <td tabindex="0" colspan="6">
  <mytemplate data="[object Object]">
   ::after
   ::before
  </mytemplate >
 </td>
</tr>
```

- Vue.js version: 2.6.12

**Comment by matfish2** [comment]
I see your template isn't rendering. How are you passing the template? 

Anyhow, Vue 2 doesn't support multiple root elements in a template. 
Also, the child row template is embedded in `tr->td` with a `colspan` of the entire table.

**Comment by GlebShu** [comment]
I connected the template as described here: https://matanya.gitbook.io/vue-tables-2/child-rows, https://matanya.gitbook.io/vue-tables-2/templates#vue-components


So I created a Vue template and exported it.
Then on the page with the table, I imported the template and registered it in the childRow.

My template vue:

```
<template>
    <tr class="funds-custom-row">
        <td tabindex="0" colspan="3">123</td>
        <td tabindex="0" colspan="3">444</td>
    </tr>
</template>

<script>
	export default {
		props: ['data', 'index'],
	}
</script>
```

On the page with the table

```
<script>
	...
	import mytemplate from '../../components/fundsCustomChildRow'
	
	export default {
		...
		templates: {
			mytemplate
		},
               data() {
                        ...
			return {
                              options: {
					childRow: 'mytemplate',
                               }
                         }
               }
```

> Also, the child row template is embedded in tr->td with a colspan of the entire table.

As I understand it, you cannot change the content exactly of the `<tr class = "VueTables__child-row">< / tr>`
How can I then insert a custom row after each row from the TableData ?

**Comment by matfish2** [comment]
replace
`childRow: 'mytemplate',`
with 
`childRow: mytemplate,`

You can try to edit `VtChildRow` and swap it to achieve the desired output (https://app.gitbook.com/@matanya/s/vue-tables-2/custom-template)

**Comment by GlebShu** [comment]
Yes, in my situation custom template it is more suitable.

> You can try to edit VtChildRow and swap it to achieve the desired output (https://app.gitbook.com/@matanya/s/vue-tables-2/custom-template)

Did as written in the documentation.

I created template 'fundsCustomChildRow':

```
<template>
    <tr :class="`VueTables__child-row ${props.class}`">
        <td :colspan="props.colspan">
            <vnodes :vnodes="props.childRow"/>
        </td>
        <td>
            <span>1233</span>
        </td>
    </tr>
</template>

<script>
	export default {
		name: "VtChildRow",
		props: ['props'],
		components: {
			vnodes: {
				functional: true,
				render: (h, ctx) => ctx.props.vnodes
			}
		}
	}
</script>
```

connection in table.js:

```
import {ClientTable, ServerTable} from 'vue-tables-2'
import Vue from 'vue'
import fundsCustomChildRow from "../components/fundsCustomChildRow";

Vue.use(
	ClientTable,
	{
		perPage: 25,
		filterByColumn: true,
		pagination: {
			chunk: 10,
			dropdown: false,
		},
		texts: {
			...
		},
		sortIcon: {
			...
		},
	},
	false,
	'bootstrap4',
	{
		VtChildRow: fundsCustomChildRow,
	},
	'default',
)
```

in the DOM:

```
<tr class="VueTables__child-row ">
    <td colspan="6"></td>
</tr>
```

And in the version of the 1.4.70,that I am using it gives an error:
tpl.call is not a function
this.$el.querySelector is not a function

**Comment by matfish2** [comment]
Custom swappable elements are only supported by v2.0 and on. Also, as per the documentation, the key to use is `childRow`, not `VtChildRow`

**Comment by GlebShu** [comment]
Ok, then please tell me why updating custom filter slots works in version 1.4 and not in version 2 ?

I use v-select and run it through v-for for: slot = "` filter__${column.key} `"
I have an empty filterOptionsItem array for options
@Search: focus event puts data from request into filterOptionsItem array.
In Table v1.4.70, after the @Search: focus event, v-select has a dropdown.  :D
Nothing happens in v2.0 table, although I can see that filterOptionsItem is not empty  :-(

```
<div v-for="(column) in filterColumns" :slot="`filter__${column.key}`"
                     :key="`${column.key}${tableFilterKey}`">
                    <v-select
                            :ref="`ref_${column.key}`"
                            :value="filters"
                            class="navigation-bar__filter-item"
                            :options.sync="filterOptionsItem"
                            :clearable="true"
                            @search:focus="sortOptions(column.key, $event)"
                            @search="sortOptions(column.key, $event)"
                            ...
                            :key="`${column.key}${tableFilterKey}`"
                    >
                        <template v-slot:no-options="{ search, searching }">
                            <template v-if="searching">
                                Nothing found by <em>{{ search }}</em>.
                            </template>
                            <em style="opacity: 0.2;" v-else>Start typing the parameter</em>
                        </template>
                    </v-select>
```
